# This version of version 24.0.0 is intended for use on macOS; the
# difference is that the static library is built as a normal library
# rather than a stand-alone library - the latter uses technology not
# available on macOS.

authors = [
"AdaCore",
]
name = "libadalang"
description = "Ada semantic analysis library (macOS version)"
licenses = "Apache-2.0 WITH LLVM-exception"
maintainers = [
"Pierre-Marie de Rodat <pmderodat@kawie.fr>",
"chouteau@adacore.com",
]
maintainers-logins = [
"pmderodat",
"Fabien-Chouteau",
]
tags = [
"libadalang",
"static-analysis",
]
version = "25.0.1"
website = "https://github.com/AdaCore/libadalang"

[available."case(os)"]
"macos" = true
"..." = false

[[depends-on]]
gnatcoll = "^25"
gnatcoll_gmp = "^25"
gnatcoll_iconv = "^25"
langkit_support = "^25"
libgpr2 = "^25"

[origin]
hashes = [
"sha512:c1ef3717adbe658a2aa04ee41c27e58a586a29f0a1c01a4a6254ee73fde68fdc05dbd9ede951d36dd1b4fa41f4b40ad8ef2958acc601bcb45c8c9ddcb53ee7a7",
]
url = "https://www.dropbox.com/scl/fi/tu2e1vs2xauof7s0s16lm/libadalang-25.0.1.zip?rlkey=uf3fypx6kdxmopngl9q00c6l3&dl=0"


