# This version of version 24.0.0 is intended for use on macOS; the
# difference is that the static library is built as a normal library
# rather than a stand-alone library - the latter uses technology not
# available on macOS.

authors = [
"AdaCore",
]
name = "libadalang"
description = "Ada semantic analysis library"
licenses = "Apache-2.0 WITH LLVM-exception"
maintainers = [
"Pierre-Marie de Rodat <pmderodat@kawie.fr>",
"chouteau@adacore.com",
]
maintainers-logins = [
"pmderodat",
"Fabien-Chouteau",
]
tags = [
"libadalang",
"static-analysis",
]
version = "24.0.1"
website = "https://github.com/AdaCore/libadalang"

[available."case(os)"]
"macos" = true
"..." = false

[[depends-on]]
gnatcoll = "^24"
gnatcoll_gmp = "^24"
gnatcoll_iconv = "^24"
langkit_support = "^24"
libgpr2 = "^24"

[origin]
hashes = [
"sha256:0a20956289cd06fc25bdb452fe8bc5c5ea8b756302ff3bedd1ef47e4e038ab07",
"sha512:dc370bed0e43d736d4cb9f0ba13afc5396c8ca24fa5500bc72e249245040aa349c9626bf3b00562d5e5757c00aed725e396644615045ece4f9b8fc9930a4d283",
]
url = "https://www.dropbox.com/scl/fi/y1wqnqs3fq0aeg000xf3s/libadalang-24.0.1.zip?rlkey=0xahe0t2zu3jbqaedkegd1cc6&dl=1"


