name = "gnat_macos"
version = "14.0.1-1"
provides = ["gnat=14.0.1-1"]
description = "The GNAT Ada compiler - Native"
maintainers = ["simon@pushface.org"]
maintainers-logins = ["simonjwright"]
licenses = "GPL-3.0-or-later AND GPL-3.0-or-later WITH GCC-exception-3.1"

auto-gpr-with = false

[configuration]
disabled = true

[environment]
PATH.prepend = "${CRATE_ROOT}/bin"

# [available."case(os)".macos."case(host-arch)"]
# "x86_64" = true
# "..." = false

[origin."case(os)".macos."case(host-arch)".x86_64]
hashes = [
"sha256:ab7115752b112fc9e34f02bc160c0eb1b8d0a6f1deaf50a645455f3f2deaacbc",
"sha512:d6a9379de90293017a59dcb369abf8aa89bd5bf46fcd1eab208f1e3ce2547aaca893d2a0bcbae4d5868c1b644b50fcb7185dd3f716b841b7488247190c089f10",
]
url = "https://github.com/simonjwright/alire-index.mac/releases/download/toolchain-13.2.1/gnat-macos-x86_64-14.0.1-1.tar.bz2"
binary = true

