name = "gprbuild"
description = "The GPRBuild Ada/multilanguage build tool"
maintainers = [
"simon@pushface.org",
]
maintainers-logins = [
"simonjwright",
]
version = "23.0.2-mac-aarch64"

auto-gpr-with = false

[configuration]
auto_gpr_with = true
disabled = true
generate_ada = true
generate_c = true
generate_gpr = true
output_dir = "config"

[environment]
PATH.prepend = "${CRATE_ROOT}/bin"

[available."case(os)".macos."case(host-arch)"]
"aarch64" = true
"..." = false

[origin."case(os)".macos."case(host-arch)".aarch64]
hashes = [
"sha256:ad45d5a7abd2b162e5b3a336b2fd39c431d4c23dbe072e19f5e727fbd4d764d3",
"sha512:d1c507e08c2c6e7eba8551582d80182a745877e26fea472031cad43c5c7b577c947bcff481d1f5837119d3eefa58bf2d2ebefee94d3391f06a82a0e1c4de9937"
]
url = "https://github.com/simonjwright/alire-index.mac/releases/download/toolchain-13.2.1/gprbuild-macos-aarch64-23.0.2.tar.gz"

