name = "gprbuild"
description = "The GPRBuild Ada/multilanguage build tool"
maintainers = [
"simon@pushface.org",
]
maintainers-logins = [
"simonjwright",
]
version = "24.0.1-mac-aarch64"

auto-gpr-with = false

[configuration]
auto_gpr_with = true
disabled = true
generate_ada = true
generate_c = true
generate_gpr = true
output_dir = "config"

[environment]
PATH.prepend = "${CRATE_ROOT}/bin"

[available."case(os)".macos."case(host-arch)"]
"aarch64" = true
"..." = false

[origin."case(os)".macos."case(host-arch)".aarch64]
hashes = [
"sha256:9e8b527a00be6a335e6b56d4264f181d3c0ebb22acc3b3af7824e8f2d54b21be",
"sha512:7027115cca7525e6e715185e4b8a7d287186bf46da6b4f1736fd5fa55abdb9ce55283f58884a85189406682d26342c0e5b7e5dd6603fe2f853b4ac22601ed48b"
]
url = "https://github.com/simonjwright/alire-index.mac/releases/download/toolchain-13.2.1/gprbuild-macos-aarch64-24.0.1.tar.gz"
binary = true
