# This version of version 24.0.0 is intended for use on macOS; the
# difference is that the static library is built as a normal library
# rather than a stand-alone library - the latter uses technology not
# available on macOS.

authors = [
"AdaCore",
]
description = "Runtime support library for Langkit-generated libraries"
licenses = "Apache-2.0 WITH LLVM-exception"
maintainers = [
"Pierre-Marie de Rodat <pmderodat@kawie.fr>",
"chouteau@adacore.com",
]
maintainers-logins = [
"pmderodat",
"Fabien-Chouteau",
]
name = "langkit_support"
version = "24.0.1"
website = "https://github.com/AdaCore/langkit"

[available."case(os)"]
"macos" = true
"..." = false

[[depends-on]]
adasat = "^24"
gnatcoll = "^24"
gnatcoll_gmp = "^24"
gnatcoll_iconv = "^24"


[origin]
hashes = [
"sha256:38875ca6308807982c2356b0c5ea25a07fdb7c08175de45367f220af507cab04",
"sha512:6fafa2736e214121ac43819eb6e928a2ec1ddcde718afae9f1766cf3f9deafeb960fa36c8b4fe024d23ca101a7fcf966535c738bf505a3c662c3b59684d7a15b",
]
url = "https://www.dropbox.com/scl/fi/20yzcb1wjlz6h5js75ob6/langkit_support-24.0.1.zip?rlkey=32qrszv7tak8dpgiyjc94mq0g&dl=1"
