# This version of version 24.0.0 is intended for use on macOS; the
# difference is that the static library is built as a normal library
# rather than a stand-alone library - the latter uses technology not
# available on macOS.

authors = [
"AdaCore",
]
description = "Runtime support library for Langkit-generated libraries (macOS version)"
licenses = "Apache-2.0 WITH LLVM-exception"
maintainers = [
"Pierre-Marie de Rodat <pmderodat@kawie.fr>",
"chouteau@adacore.com",
]
maintainers-logins = [
"pmderodat",
"Fabien-Chouteau",
]
name = "langkit_support"
project-files = [
"langkit/support/langkit_support.gpr",
]
version = "25.0.1"
website = "https://github.com/AdaCore/langkit"

[available."case(os)"]
"macos" = true
"..." = false

[[depends-on]]
adasat = "^25"
gnatcoll = "^25"
gnatcoll_gmp = "^25"
gnatcoll_iconv = "^25"
prettier_ada = "^25"

[origin]
hashes = [
"sha512:f7e331c4d61bd96c26123b4380c5e06f76571d7b19e185a9ac7de9a147b97b43fd683ab9195384b9a4a8d589e2cb9802dccc7cdeae7af5584aef2a80f23521bc",
]
url = "https://www.dropbox.com/scl/fi/zeh2jh89ssymkyaspjtdm/langkit_support-25.0.1.zip?rlkey=y39cwhrn3knj22kdqoos5xgn5&dl=0"
