name = "gnat_macos_aarch64"
version = "13.1.1"
provides = ["gnat=13.1.1"]
description = "The GNAT Ada compiler - Native"
maintainers = ["simon@pushface.org"]
maintainers-logins = ["simonjwright"]
licenses = "GPL-3.0-or-later AND GPL-3.0-or-later WITH GCC-exception-3.1"

auto-gpr-with = false

[configuration]
disabled = true

[environment]
PATH.prepend = "${CRATE_ROOT}/bin"

[available."case(os)".macos."case(host-arch)"]
"aarch64" = true
"..." = false

[origin]
hashes = [
"sha256:a8cde682425819599883372b08505135565f4cf058b4f4cb88b452cc660ebce9",
"sha512:851453c0e6078f5e6776b202436edc0de6c8c0100923e647e716954dfdba4967ff142bec7a8bc7eccff31033061c81b3bb8150b14c3f504e6198ceefa83beb69",
]
url = "https://www.dropbox.com/scl/fi/oj97xg1x78fzvsae1ufww/gnat-macos-aarch64-13.1.1.tar.gz?rlkey=1t1qwcguvxgn4rybq2xi2pudv&dl=0"

