name = "gnat_macos_aarch64"
version = "13.1.0"
provides = ["gnat=13.1.0"]
description = "The GNAT Ada compiler - Native"
maintainers = ["simon@pushface.org"]
maintainers-logins = ["simonjwright"]
licenses = "GPL-3.0-or-later AND GPL-3.0-or-later WITH GCC-exception-3.1"

auto-gpr-with = false

[configuration]
disabled = true

[environment]
PATH.prepend = "${CRATE_ROOT}/bin"

[available."case(os)".macos."case(host-arch)"]
"aarch64" = true
"..." = false

[origin]
hashes = [
"sha256:66361b2f0ab649c48d2c17e7853de080ec5d245c5f9152da1d03fe6a9232f79b",
"sha512:b3b8d1447e5a0e5d1bfad90341fb17fb096d0310fcbf476afdebfec2334ff0cc966af0de68b17297d8f7f68a3111cd97b0dc9031ec173e01c5e2d13090987667",
]
url = "https://www.dropbox.com/s/csy0dsdk0skr6vi/gnat-macos-aarch64-13.1.0.tar.gz"

